server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgblog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: zengchen
    password: zengchen233
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  #mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.zengchen233.entity